version: "3.9"

services:
  fluentd:
    container_name: fluentd
    build: ./fluentd
    volumes:
      - ./tmp/fluentd/conf:/fluentd/etc
    links:
      - "elasticsearch"
    ports:
      - "24224:24224"
      - "24224:24224/udp"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.2
    container_name: elasticsearch
    restart: always
    environment:
      bootstrap.memory_lock: "true"
      xpack.security.enabled: "true"
      discovery.type: single-node
      ELASTIC_PASSWORD: password1234
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - ./tmp/elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:8.6.2
    restart: always
    environment:
      SERVERNAME: kibana
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
      ELASTICSEARCH_USERNAME: kibana_system
      ELASTICSEARCH_PASSWORD: password1234
      XPACK_SECURITY_ENABLED: "true"
    ports:
      - "5601:5601"
    volumes:
      - ./tmp/kibana-data:/usr/share/kibana/data
    depends_on:
      - elasticsearch
volumes:
  elasticsearch-data:
  kibana-data:

